// 单一真相源：src-tauri/tauri.conf.json 的 "version"
// 本脚本把版本同步到所有需要它的位置，避免发版时手动改多处导致不一致。
// 由 `npm run sync:version` 或 `pretauri` 钩子自动调用，也可手动跑。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..'); // scripts/.. = 项目根

const confPath = path.join(root, 'src-tauri/tauri.conf.json');
const cargoPath = path.join(root, 'src-tauri/Cargo.toml');
const pkgPath = path.join(root, 'package.json');
const liveCoreVer = path.join(root, 'desktop_core/version.json');
const snapCoreVer = path.join(root, 'src-tauri/resources/desktop_core/version.json');
const releaseCoreVer = path.join(root, 'src-tauri/target/release/resources/desktop_core/version.json');
const tsPath = path.join(root, 'src/lib/version.ts');
const readmePath = path.join(root, 'README.md');
const readmeEnPath = path.join(root, 'README_EN.md');

function readVersion() {
  const conf = JSON.parse(fs.readFileSync(confPath, 'utf8'));
  const v = conf.version;
  if (!v || !/^\d+\.\d+\.\d+/.test(v)) {
    console.error('[sync-version] tauri.conf.json 缺少合法 version 字段');
    process.exit(1);
  }
  return v;
}

const version = readVersion();

// 1) Cargo.toml — [package] 段的 version（行首锚定，避免命中依赖版本）
let cargo = fs.readFileSync(cargoPath, 'utf8');
cargo = cargo.replace(/^version = ".*"$/m, `version = "${version}"`);
fs.writeFileSync(cargoPath, cargo);

// 2) package.json — 仅替换首个 "version" 字段，保留其余格式/注释
let pkg = fs.readFileSync(pkgPath, 'utf8');
pkg = pkg.replace(/"version":\s*"[^"]*"/, `"version": "${version}"`);
fs.writeFileSync(pkgPath, pkg);

// 3) desktop_core/version.json — 活代码、打包快照、运行时三处（运行时可能尚未打包，跳过不存在的）
const vj = JSON.stringify({ version }, null, 2) + '\n';
for (const p of [liveCoreVer, snapCoreVer, releaseCoreVer]) {
  try {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, vj);
  } catch (e) {
    // target/release 可能不存在（未打包），忽略
  }
}

// 4) src/lib/version.ts — 前端 fallback 用（getVersion 失败/非 Tauri 环境）
fs.mkdirSync(path.dirname(tsPath), { recursive: true });
fs.writeFileSync(tsPath,
  `// AUTO-GENERATED by scripts/sync-version.mjs — 不要手改；改 src-tauri/tauri.conf.json 后跑 npm run sync:version\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n` +
  `export const APP_FALLBACK_VERSION = ${JSON.stringify(version)};\n`);

// 5) README 徽章 + 快速开始下载文件名（避免发版后 README 仍写旧版本号，#5）
// ★ 中英两份都要同步（2026-09-22）：此前只处理 README.md，导致 README_EN.md 的徽章与下载名
//   长期停在旧版本（1.0.1 发布时它的徽章还写着 v1.0.0，用户看到的英文页是过期的）。
function syncReadme(file) {
  if (!fs.existsSync(file)) return false;
  let s = fs.readFileSync(file, 'utf8');
  let changed = false;
  const fix = (re, want) => {
    s = s.replace(re, (m) => {
      if (m !== want) changed = true;
      return want;
    });
  };

  const badge = `![Release](https://img.shields.io/badge/Release-v${version}-blue)`;
  // 下载名：必须与 GitHub Release 实际上传的资产名一致（历史均用 naixi-desktop_*，
  // 且资产名须 ASCII，故不能用中文 productName 前缀 奶昔_*，否则 README 下载链接 404）。
  const dl = `naixi-desktop_${version}_x64-setup.exe`;

  fix(/!\[Release\]\(https:\/\/img\.shields\.io\/badge\/Release-v[0-9]+\.[0-9]+\.[0-9]+-blue\)/g, badge);
  fix(/naixi-desktop_[0-9]+\.[0-9]+\.[0-9]+_x64-setup\.exe/g, dl);

  if (s.includes('这是 ') || file === readmePath) {
    // 中文版：代码签名说明段 + 「已知问题」开头的真实边界（历史上漏同步会变成陈旧承诺）
    fix(/当前 [0-9]+\.[0-9]+\.[0-9]+ 安装包使用自签名证书/g, `当前 ${version} 安装包使用自签名证书`);
    fix(/这是 [0-9]+\.[0-9]+\.[0-9]+ 的真实边界/g, `这是 ${version} 的真实边界`);
  }
  if (file === readmeEnPath) {
    // 英文版：同上两处（发布后忘记同步会给出过期的英文承诺）
    fix(/The [0-9]+\.[0-9]+\.[0-9]+ installer uses/g, `The ${version} installer uses`);
    fix(/The honest boundary of [0-9]+\.[0-9]+\.[0-9]+:/g, `The honest boundary of ${version}:`);
  }

  if (changed) fs.writeFileSync(file, s);
  return changed;
}

const readmeChanged = syncReadme(readmePath);
const readmeEnChanged = syncReadme(readmeEnPath);

console.log(`[sync-version] 已同步版本 -> ${version}`);
console.log('  来源: src-tauri/tauri.conf.json');
console.log('  已写: src-tauri/Cargo.toml / package.json / desktop_core/version.json(x3) / src/lib/version.ts');
console.log('  已同步: README.md 与 README_EN.md 的徽章 / 快速开始下载名 / 版本相关段落');
console.log('  前端运行时仍优先用 getVersion() 读 tauri.conf.json，以上仅为兜底/构建期注入。');
