// 单一真相源：src-tauri/tauri.conf.json 的 "version"
// 本脚本把版本同步到所有需要它的位置，避免发版时手动改多处导致不一致。
// 由 `npm run sync:version` 或 `pretauri` 钩子自动调用，也可手动跑。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..'); // scripts/.. = 项目根

const confPath = path.join(root, 'src-tauri/tauri.conf.json');
const cargoPath = path.join(root, 'src-tauri/Cargo.toml');
const pkgPath = path.join(root, 'package.json');
const liveCoreVer = path.join(root, 'desktop_core/version.json');
const snapCoreVer = path.join(root, 'src-tauri/resources/desktop_core/version.json');
const releaseCoreVer = path.join(root, 'src-tauri/target/release/resources/desktop_core/version.json');
const tsPath = path.join(root, 'src/lib/version.ts');
const readmePath = path.join(root, 'README.md');

function readVersion() {
  const conf = JSON.parse(fs.readFileSync(confPath, 'utf8'));
  const v = conf.version;
  if (!v || !/^\d+\.\d+\.\d+/.test(v)) {
    console.error('[sync-version] tauri.conf.json 缺少合法 version 字段');
    process.exit(1);
  }
  return v;
}

const version = readVersion();

// 1) Cargo.toml — [package] 段的 version（行首锚定，避免命中依赖版本）
let cargo = fs.readFileSync(cargoPath, 'utf8');
cargo = cargo.replace(/^version = ".*"$/m, `version = "${version}"`);
fs.writeFileSync(cargoPath, cargo);

// 2) package.json — 仅替换首个 "version" 字段，保留其余格式/注释
let pkg = fs.readFileSync(pkgPath, 'utf8');
pkg = pkg.replace(/"version":\s*"[^"]*"/, `"version": "${version}"`);
fs.writeFileSync(pkgPath, pkg);

// 3) desktop_core/version.json — 活代码、打包快照、运行时三处（运行时可能尚未打包，跳过不存在的）
const vj = JSON.stringify({ version }, null, 2) + '\n';
for (const p of [liveCoreVer, snapCoreVer, releaseCoreVer]) {
  try {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, vj);
  } catch (e) {
    // target/release 可能不存在（未打包），忽略
  }
}

// 4) src/lib/version.ts — 前端 fallback 用（getVersion 失败/非 Tauri 环境）
fs.mkdirSync(path.dirname(tsPath), { recursive: true });
fs.writeFileSync(tsPath,
  `// AUTO-GENERATED by scripts/sync-version.mjs — 不要手改；改 src-tauri/tauri.conf.json 后跑 npm run sync:version\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n` +
  `export const APP_FALLBACK_VERSION = ${JSON.stringify(version)};\n`);

// 5) README 徽章 + 快速开始下载文件名（避免发版后 README 仍写旧版本号，#5）
if (fs.existsSync(readmePath)) {
  let readme = fs.readFileSync(readmePath, 'utf8');
  let changed = false;
  // 徽章：![Release](https://img.shields.io/badge/Release-vX.Y.Z-blue)
  const newBadge = `![Release](https://img.shields.io/badge/Release-v${version}-blue)`;
  readme = readme.replace(/!\[Release\]\(https:\/\/img\.shields\.io\/badge\/Release-v[0-9]+\.[0-9]+\.[0-9]+-blue\)/, (m) => {
    if (m !== newBadge) changed = true;
    return newBadge;
  });
  // 快速开始下载名：naixi-desktop_X.Y.Z_x64-setup.exe
  // 注意：必须与 GitHub Release 实际上传的资产名一致（历史均用 naixi-desktop_*，
  // 且资产名须 ASCII，故不能用中文 productName 前缀 奶昔_*，否则 README 下载链接 404）。
  const newDl = `naixi-desktop_${version}_x64-setup.exe`;
  readme = readme.replace(/naixi-desktop_[0-9]+\.[0-9]+\.[0-9]+_x64-setup\.exe/g, (m) => {
    if (m !== newDl) changed = true;
    return newDl;
  });
  // 代码签名说明段里的版本号（「当前 X.Y.Z 安装包尚未做代码签名」）
  readme = readme.replace(/当前 [0-9]+\.[0-9]+\.[0-9]+ 安装包尚未做代码签名/, (m) => {
    const want = `当前 ${version} 安装包尚未做代码签名`;
    if (m !== want) changed = true;
    return want;
  });
  if (changed) fs.writeFileSync(readmePath, readme);
}

console.log(`[sync-version] 已同步版本 -> ${version}`);
console.log('  来源: src-tauri/tauri.conf.json');
console.log('  已写: src-tauri/Cargo.toml / package.json / desktop_core/version.json(x3) / src/lib/version.ts');
console.log('  已同步: README.md 徽章 / 快速开始下载名 / 代码签名说明段');
console.log('  前端运行时仍优先用 getVersion() 读 tauri.conf.json，以上仅为兜底/构建期注入。');
