// 单一真相源：src-tauri/tauri.conf.json 的 "version"
// 本脚本把版本同步到所有需要它的位置，避免发版时手动改多处导致不一致。
// 由 `npm run sync:version` 或 `pretauri` 钩子自动调用，也可手动跑。
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..'); // scripts/.. = 项目根

const confPath = path.join(root, 'src-tauri/tauri.conf.json');
const cargoPath = path.join(root, 'src-tauri/Cargo.toml');
const pkgPath = path.join(root, 'package.json');
const liveCoreVer = path.join(root, 'desktop_core/version.json');
const snapCoreVer = path.join(root, 'src-tauri/resources/desktop_core/version.json');
const releaseCoreVer = path.join(root, 'src-tauri/target/release/resources/desktop_core/version.json');
const tsPath = path.join(root, 'src/lib/version.ts');

function readVersion() {
  const conf = JSON.parse(fs.readFileSync(confPath, 'utf8'));
  const v = conf.version;
  if (!v || !/^\d+\.\d+\.\d+/.test(v)) {
    console.error('[sync-version] tauri.conf.json 缺少合法 version 字段');
    process.exit(1);
  }
  return v;
}

const version = readVersion();

// 1) Cargo.toml — [package] 段的 version（行首锚定，避免命中依赖版本）
let cargo = fs.readFileSync(cargoPath, 'utf8');
cargo = cargo.replace(/^version = ".*"$/m, `version = "${version}"`);
fs.writeFileSync(cargoPath, cargo);

// 2) package.json — 仅替换首个 "version" 字段，保留其余格式/注释
let pkg = fs.readFileSync(pkgPath, 'utf8');
pkg = pkg.replace(/"version":\s*"[^"]*"/, `"version": "${version}"`);
fs.writeFileSync(pkgPath, pkg);

// 3) desktop_core/version.json — 活代码、打包快照、运行时三处（运行时可能尚未打包，跳过不存在的）
const vj = JSON.stringify({ version }, null, 2) + '\n';
for (const p of [liveCoreVer, snapCoreVer, releaseCoreVer]) {
  try {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, vj);
  } catch (e) {
    // target/release 可能不存在（未打包），忽略
  }
}

// 4) src/lib/version.ts — 前端 fallback 用（getVersion 失败/非 Tauri 环境）
fs.mkdirSync(path.dirname(tsPath), { recursive: true });
fs.writeFileSync(tsPath,
  `// AUTO-GENERATED by scripts/sync-version.mjs — 不要手改；改 src-tauri/tauri.conf.json 后跑 npm run sync:version\n` +
  `export const APP_VERSION = ${JSON.stringify(version)};\n` +
  `export const APP_FALLBACK_VERSION = ${JSON.stringify(version)};\n`);

console.log(`[sync-version] 已同步版本 -> ${version}`);
console.log('  来源: src-tauri/tauri.conf.json');
console.log('  已写: src-tauri/Cargo.toml / package.json / desktop_core/version.json(x3) / src/lib/version.ts');
console.log('  前端运行时仍优先用 getVersion() 读 tauri.conf.json，以上仅为兜底/构建期注入。');
